# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# plugins:

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

include:
  - _pages
  - _redirects

# Site settings
title: Marta Małecka
long-title: Marta Małecka
email: mmartamaleckan@gmail.com
description: "Portfolio"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mmartamalecka.pl" # the base hostname & protocol for your site
timezone: Europe/Warsaw
year: 2025
start-year: 2010
sitemap: true


# Content
image_serve_path: "/images-compressed" # <img src="{{ site.image_serve_path }}/projects/img.jpg">

# Build settings
markdown: kramdown

kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Sass output
sass:
  style: compressed # :nested :compact :expanded :compressed

compress_html: # http://jch.penibelst.de/
  enabled: true # compress html
  clippings: all # clip safe tags
  comments: []
  endings: []
  #ignore:
    #envs: [local]
  blanklines: false # boolean - strip blank lines and breaks
  profile: false
  startings: []


# Structure
navigation:
  - title: HOME
    url: /
  - title: DESIGN
    url: /projektowanie
  - title: ANIMATION & VIDEO
    url: /video
  - title: ABOUT
    url: /about

permalink: /:title/

# Configure site collections
collections:
  projects:
    output: true
    permalink: /projects/:path/


defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

